version: "3.9"

services:
  classmodel-backend:
    build:
      context: backend/classmodel
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - backend/classmodel/.env
    volumes:
      - ./backend/classmodel:/app
      - ./backend/classmodel/gcp.json:/tmp/gcp_creds.json:ro

    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]

  regmodel-backend:
    build:
      context: backend/regmodel
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/regmodel/.env
    volumes:
      - ./backend/regmodel:/app
    command: ["uvicorn", "app.fastapi_app:app", "--host", "0.0.0.0", "--port", "8000"]